### PR TITLE
OpenAPI 3.0 Support For SecurityDefinitions

### PR DESCRIPTION
**Pull request by joseph-montanez**
It looks like security definitions was renamed to "securitySchema" and place under "components". I've added support for this with a test units, and updated the configuration file to show an example of an Open API 3.0 security schema as its a little different than Swagger / Open API 2.0.

### CODE REVIEW

**Comment by DarkaOnLine** [comment]
@joseph-montanez Thanks! Great job. Just one question/suggestion.

For me and also fo CodeClimate - `appendSecurityDefinisions` function is too complex now. Can you refactor it to a separate class?

**Comment by DarkaOnLine** [comment]
@joseph-montanez looks great. Are you finished?

**Comment by joseph-montanez** [comment]
@DarkaOnLine Sorry I was running to code coverage, and then ensuring tests only run for the OpenAPI / Swagger version needed. The plumbing was already there I was just not using it. I'll see if this last push fixes it.

**Comment by joseph-montanez** [comment]
Alright I am done but stuck on code coverage. Certain code should not be executed depending on the version of swagger/open api, this is affected code coverage results.

**Comment by DarkaOnLine** [comment]
@jm-comentum Thank you again for your Great job!!! 🎉

**Pull request merged**
