### PR TITLE
Incluido o filtro padrao do swagger para aparecer na pagina

### PR DESCRIPTION
**Pull request by GustavoSantarosa**
Incluido o filtro padrao do swagger, uma otima ferramenta de busca para as rotas.

Por padrão, mantive true para ja aparecer, mas ai tem a opção de colocar false

### CODE REVIEW

**Comment by DarkaOnLine** [comment]
Thanks for PR. Can you please write everything in English? Also please fix failing styling as it is failing now in CI

**Comment by DarkaOnLine** [comment]
Added in https://github.com/DarkaOnLine/L5-Swagger/commit/fed4f7b8a6c9cfa36ff2cd299d72fea291f92653

**Comment by GustavoSantarosa** [comment]
could have merged from my branch, I wanted to become a contributor. @DarkaOnLine

**Comment by GustavoSantarosa** [comment]
I thought it was rude

**Pull request closed without merging**
