### PR TITLE
update composer.json to support Laravel 5.4

### PR DESCRIPTION
**Pull request by KillermenBE**

### CODE REVIEW

**Comment by DarkaOnLine** [comment]
Travis is sad, can you check it?

**Comment by KillermenBE** [comment]
`$this->app->share()` is deprecated, so I changed to Singleton and now I get another message. 
I will try to fix this when I'm at the office tomorrow.

**Comment by DarkaOnLine** [comment]
Would be great. Because I am on vocation and will be able to look at it only  on Monday :(

**Comment by KillermenBE** [comment]
There's something wrong with `Artisan::call`. Even if I change it around to `migrate` it doens't work and I get the same error. Maybe a bug in L5.4?

**Comment by DarkaOnLine** [comment]
Fixed in #52

**Pull request closed without merging**
