### PR TITLE
[BUG_FIX] Changes  \Swagger namespace to \OpenApi

### PR DESCRIPTION
**Pull request by ejbogantes**
- Last update on https://github.com/zircote/swagger-php changes  \Swagger namespace to \OpenApi
- Also annotations prefix changed from @OAS to @OA.

### CODE REVIEW

**Comment by DarkaOnLine** [comment]
Can some one test and approve this? I am on vocation and can't test it for two more weeks!

**Comment by ejbogantes** [comment]
@DarkaOnLine this is a **MAJOR** change, swagger-php recently changed this annotations and broke my project with the last version. (OpenApi 3.0)

**Comment by DarkaOnLine** [comment]
Does it mean we have to release 5.7.0? I wanted to mirror laravel releases with 5.x.
Is swagger-php 3.x is stable now?

**Comment by DarkaOnLine** [comment]
If swagger-php is not stable yet we can tag it as minor change, cause it is supported as unstable now also. I will tag it blindly and hope that it will be 👌

**Comment by ejbogantes** [comment]
OK excellent!

**Pull request merged**
